### ISSUE TITLE
节点挂掉后重启，前置服务链接会报错

### ISSUE THREAD

**Issue by Skkypy** [WeBankBlockchain/WeBASE-Front#748]
当前置服务链接的节点挂掉，重启节点。前置服务（未重启）取链上信息报错：
```
com.webank.webase.front.base.exception.FrontException: No available node to connect
	at com.webank.webase.front.web3api.Web3ApiService.checkConnection(Web3ApiService.java:852) ~[WeBASE-Front.jar:?]
	at com.webank.webase.front.web3api.Web3ApiService.getWeb3j(Web3ApiService.java:820) ~[WeBASE-Front.jar:?]
```
前置服务重启后，正常。

**Comment by CodingCattwo** [comment]
可以调用/web3/1/refresh 刷新连接池，尝试重连节点
