### ISSUE TITLE
5002启动不了

### ISSUE THREAD

**Issue by feiyecyf** [WeBankBlockchain/WeBASE-Front#779]
===============================================================================================
Server com.webank.webase.front.Application Port 5002 ...PID(6079) [Starting]. Please check message through the log file (default path:./log/).
===============================================
bash status.sh
===============================================================================================
Server com.webank.webase.front.Application Port 5002 is not running
===============================================================================================
zgxt@zgxt-virtual-machine:~/webase-front/log$ tail -f WeBASE-Front.log
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:211) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1134) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1062) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.29.RELEASE.jar:4.3.29.RELEASE]
	... 19 more

**Comment by CodingCattwo** [comment]
日志中未定位到关键错误，建议按照webase文档中快速部署或一键部署的文档进行排查

**Comment by tannnn2022** [comment]
请问，问题解决了吗？我也遇到相同问题了，求解

**Comment by feiyecyf** [comment]
解决了，目录错误的问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tannnn2022 ***@***.***&gt;
发送时间: 2022年8月14日 16:05
收件人: WeBankBlockchain/WeBASE-Front ***@***.***&gt;
抄送: feiyecyf ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[WeBankBlockchain/WeBASE-Front] 5002启动不了 (Issue #779)





 
请问，问题解决了吗？我也遇到相同问题了，求解

**Comment by lovecuit** [comment]
你好 具体是怎么解决的呢，我也遇见这个问题

**Comment by feiyecyf** [comment]
webase的目录要建在fisco目录下面，不能建在根目录下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月15日(星期一) 上午10:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WeBankBlockchain/WeBASE-Front] 5002启动不了 (Issue #779)





 
你好 具体是怎么解决的呢，我也遇见这个问题
